### ISSUE TITLE
Ship-initiative not working if ship is not in combat

### ISSUE THREAD

**Issue by kagedansa** [kbender84/token-action-hud-coriolis#3]
If the ship-token has not been added to a combat yet, no dice roll is triggered and the following messages appear in the console

![image](https://github.com/kbender84/token-action-hud-coriolis/assets/110729103/3413d0e1-a7ff-4b67-91ae-d8efe5ecfd7b)

Perhaps it would be useful to check that and add the token to the combat first

**Comment by kbender84** [comment]
Hi, this is tricky one.
What is expected output?
Should the ini roll add ship to combat queue or should it check if the ship is in combat and simply do nothing if it's not? Or something else?

**Comment by kagedansa** [comment]
I think it would be enough to call up the following beforehand:

await canvas.tokens.toggleCombat();

There should be no problems if the token is already in combat.

**Comment by kbender84** [comment]
![obraz](https://github.com/kbender84/token-action-hud-coriolis/assets/66570321/ffc2a869-8ccd-4251-8765-4ff3d332c033)
Not a perfect solution, but should be good enough.
Async canvas didn't work because the module is using different syntax (api) than macros.
But at least there's nice notification now, and no error in logs.

**Comment by kbender84** [comment]
fixed in release 1.1.4, please test

**Comment by kagedansa** [comment]
Works for me. Thank you!
